### PR TITLE
Remove extra angle brackets

### PR DESCRIPTION
**Pull request by cesarlr**

### CODE REVIEW

**Comment by cesarlr** [comment]
@remytms @vvrossem @mclaeysb Fixing a pair of typos

**Review by vvrossem — APPROVED** [review]

**Comment by vvrossem** [comment]
@cesarlr good catch ! :mag:

**Comment by cesarlr** [comment]
@vvrossem Sorry I forgot one more typo

**Review by enricostano — APPROVED** [review]

**Comment by enricostano** [comment]
cc/ @robinkeunen

**Pull request merged**
