### PR TITLE
Translate French source strings

### PR DESCRIPTION
**Pull request by carmenbianca**
## Description

Tagged French source strings in all l10n modules.

Updated all .pot files as part of this process to find the source strings more easily.

## Checklist before approval

- [ ] Translate the tagged lines.
- [ ] Verify absence of French source strings from non-l10n modules

### CODE REVIEW

**Comment by carmenbianca** [comment]
dfe2eef4d82f20749a7232de6a289472fd2ed873 is the relevant commit here.

**Comment by carmenbianca** [comment]
Might be a better idea to drop the UPD commits. They're going to conflict with all the `sed` renaming going on.

**Comment by victor-champonnois** [comment]
@carmenbianca 
- I don't understand what this PR does, could you explain a bit more ? What are tagged lines ?
- Is it somehow related to this issue https://github.com/coopiteasy/vertical-cooperative/issues/294 ?

**Comment by carmenbianca** [comment]
@victor-champonnois 

1. [dfe2eef](https://github.com/coopiteasy/vertical-cooperative/pull/270/commits/dfe2eef4d82f20749a7232de6a289472fd2ed873) is the only relevant commit. Maybe also [581f05d](https://github.com/coopiteasy/vertical-cooperative/pull/270/commits/581f05d6704e9dc4d027203d3715718027adc22d). The rest can be effectively removed. There is French text in the code. OCA will only accept the code if the strings are in English.
2. That's what all the other commits are about. But they're outdated now. We can wait with this.

**Comment by victor-champonnois** [comment]
@carmenbianca OK thanks for your reply, I'll delete the unnecessary commits and merge the PR. I am working on translations now and it's a mess, so I prefer to move on with this :)

**Pull request merged**
