### PR TITLE
[14.0][REM] cooperator

### PR DESCRIPTION
**Pull request by huguesdk**
move to [oca's cooperative](https://github.com/OCA/cooperative) repository.

### CODE REVIEW

**Review by carmenbianca — APPROVED** [review]
LGTM

Make sure to remove the dependency on `cooperator` from the `test-requirements.txt` of dependent repos.

**Comment by robinkeunen** [comment]
@remytms can I merge this ?

**Comment by huguesdk** [comment]
this can be merged, but we must ensure that if this change is put in production, the [OCA/cooperative](https://github.com/OCA/cooperative) repository is added to the configuration.

**Pull request merged**
