### PR TITLE
Fixed bad format date when no payment

### PR DESCRIPTION
**Pull request by cesarlr**

### CODE REVIEW

**Comment by cesarlr** [comment]
@houssine78 @robinkeunen An error happens when no payment lines. The format of the date in that line is not ISO, so it throws an error during creation. In Odoo 12 is not needed to format dates as string

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by houssine78** [comment]
We'll need to test that before merging to just be sure it do not break anything from our side.

**Comment by houssine78** [comment]
@cesarlr I just deployed it on our test server. we wait for the feedback of our analysts.

Many thanks for the provided bug fix !

**Comment by robinkeunen** [comment]
@houssine78 did you get any feedback?

**Review by robinkeunen — APPROVED** [review]

**Comment by houssine78** [comment]
@robinkeunen no, I asked Catherine to test it. But I think she didn't found the time to do it.

**Comment by robinkeunen** [comment]
@cesarlr I'm trying to reproduce, I don't understand how you can mark an invoice as paid without payment lines. Can you add a unit test to reproduce?

I'll try to be more reactive on this PR.

**Comment by robinkeunen** [comment]
Also, I'd write it like this:

```python 
                if invoice.payment_move_line_ids:
                    move_line = invoice.payment_move_line_ids[0]
                    effective_date = move_line.date
                else:
                    effective_date = datetime.now()
```

**Pull request merged**
