### PR TITLE
[12.0][REM] cooperator

### PR DESCRIPTION
**Pull request by huguesdk**
move to [oca's cooperative](https://github.com/OCA/cooperative) repository.

### CODE REVIEW

**Review by carmenbianca — APPROVED** [review]
LGTM.

Same comment as on 14.0 in re removal of cooperator from `test-requirements.txt` in dependent repos.

**Comment by robinkeunen** [comment]
@remytms can I merge this ?

**Comment by huguesdk** [comment]
this should preferably have been merged before the deployment of 2022-10-31, since the [OCA/cooperative](https://github.com/OCA/cooperative) repository was added. it is not really a problem, but we need to keep in mind that currently the modules that are in the oca’s repository are there twice, and that it is the ones from this repository that are used instead (because this repository is before the oca’s one in `addons_path`).

what to do now? this can be merged now, but we must ensure that this change is released and put in production during the next deployment. currently the prod uses the `12.0-2022-09-09.00` tag of this repository.

**Pull request merged**
