### PR TITLE
[14.0][MIG] portal_recaptcha

### PR DESCRIPTION
**Pull request by carmenbianca**
## Odoo task (if applicable)

https://gestion.coopiteasy.be/web#id=8773&action=475&active_id=260&model=project.task&view_type=form&menu_id=

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

### CODE REVIEW

**Comment by victor-champonnois** [comment]
@carmenbianca is the porting done or is there still some work to do?

**Review by huguesdk — APPROVED** [review]

**Review by carmenbianca — COMMENTED** [review]
can't approve own PR, but reviewed this and it looks OK.

**Pull request merged**
