### PR TITLE
Apply oca-addons-repo-template

### LINKED ISSUE #225: Align Coop IT Easy CI to OCA CI

### PR DESCRIPTION
**Pull request by carmenbianca**
Fixes #225

### CODE REVIEW

**Comment by carmenbianca** [comment]
I guess there's a good reason eslint was disabled :x my word that's a backlog.

**Comment by robinkeunen** [comment]
Yes, there's this js library that was completely copied here for - i guess - one function. I'd love to get rid of that library. There's a komunigi task about that.

**Comment by carmenbianca** [comment]
Created an issue for that in #227

**Comment by carmenbianca** [comment]
'Detect unreleased dependencies' is failing because the dependencies are URLs. This is not behaviour that we want. I'll disable that test in our patchset and here.

**Comment by carmenbianca** [comment]
@robinkeunen @coccinouille Ready to merge.

**Pull request merged**
