### PR TITLE
[REM] cooperator: jquery.inputmask.bundle.js

### LINKED ISSUE #227: Remove jquery.inputmask.bundle.js
Task: https://gestion.coopiteasy.be/web#id=8191&view_type=form&model=project.task&action=475&active_id=221

### PR DESCRIPTION
**Pull request by robinkeunen**
inputmask was used in version 9 to force the formatting of birthdate in the subscription request form. It is no longer useful and allows to enable eslint.

@polchampion you can test that the subscription request form on any db is still working. No UX changes especially not on the birthdate.

Will port in v14

fixes https://github.com/coopiteasy/vertical-cooperative/issues/227

### CODE REVIEW

**Comment by huguesdk** [comment]
note: this file has been moved to `cooperator_website` in 14.0 and in #375.

edit: ok, did not see that is was a branch originating from [`12.0-backport_mig_14_changes_cooperator_website`](https://github.com/coopiteasy/vertical-cooperative/tree/12.0-backport_mig_14_changes_cooperator_website).

**Review by polchampion — APPROVED** [review]
Functional test successful on `lepedalo-test`

**Review by huguesdk — APPROVED** [review]
lgtm. thanks for this! 🎉👍

**Comment by robinkeunen** [comment]
ah non, je dois juste merger dans ta pr celle-ci.

**Pull request merged**
