### PR TITLE
[14.0][MIG] l10n_be_cooperator

### PR DESCRIPTION
**Pull request by victor-champonnois**
## Description
Porting l10n_be_cooperator to 14.0

## Odoo task (if applicable)
https://gestion.coopiteasy.be/web#id=8756&action=475&active_id=260&model=project.task&view_type=form&menu_id=536

### CODE REVIEW

**Review by carmenbianca — COMMENTED** [review]
LGTM, but we'll wait for the tests to be able to run.

I would also drop adba3e13e1aef0c7f7334c26ba9eea12d9cc8d04 and a61e9aa0c5c9d3218658096dc7cfd39981f8797b

**Comment by carmenbianca** [comment]
@victor-champonnois I think something went wrong. You just force-pushed 632 commits.

**Comment by victor-champonnois** [comment]
@carmenbianca ah yes, the base was wrong

**Comment by polchampion** [comment]
@huguesdk

**Review by huguesdk — APPROVED** [review]

**Review by carmenbianca — APPROVED** [review]

**Pull request merged**
