### PR TITLE
Add structure to publish in Pypi with Odoo Setuptools the EMC API module

### PR DESCRIPTION
**Pull request by danypr92**

### CODE REVIEW

**Review by robinkeunen — COMMENTED** [review]
I have no idea how that stuff works :/ maybe you could get a review from someone else at coopdev?

**Comment by cesarlr** [comment]
I have the same changes at my computer. It's a good idea to upload the setup to main repository

**Comment by danypr92** [comment]
Yes @robinkeunen, I agree. I can ask for the review to @enricostano and @cesarlr.

**Comment by enricostano** [comment]
:+1:

**Comment by robinkeunen** [comment]
Ok to merge then?

**Comment by cesarlr** [comment]
Yes!

**Comment by danypr92** [comment]
:tada: :tada: :tada: :tada:

**Pull request merged**
