### PR TITLE
[12.0] Rename easy_my_coop_api to cooperator_api

### LINKED ISSUE #213: Rename `easy_my_coop_api` to ` cooperator_api`
- [ ]  Rename `easy_my_coop_api` to ` cooperator_api`

Estimated time - 16h

Module contains these functionalities :
- Easy my Coop RESTful API

### PR DESCRIPTION
**Pull request by carmenbianca**
## Description

Fixes #213

look at this amazing new github pr template. it needs some work

I also grabbed easy_my_coop_api_logs and renamed it to cooperator_api_logs. However, I don't think I understand why this is a separate module, when easy_my_coop explicitly depends on it.

## Odoo task (if applicable)

n/a

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] (If a new module) Moving this to OCA has been considered.
- [ ] After #202 is merged, rebase on top of 12.0

### CODE REVIEW

**Comment by carmenbianca** [comment]
@robinkeunen This has doubtlessly been discussed, but what do we do about stuff like [cooperator_api_logs/models/emc_api_log.py](https://github.com/coopiteasy/vertical-cooperative/blob/074e15bf439d9a321cd520f80fc96a4942397885/cooperator_api_logs/models/emc_api_log.py)? Do we rename it? If we rename it, do we also change the `_name` variable? Does this need a migration script, or are we fine with keeping stuff as-is as a sort of legacy implementation detail?

**Comment by robinkeunen** [comment]
Renaming file and model names will be done in a second step, cf battle plan : https://github.com/coopiteasy/vertical-cooperative/issues/204

**Comment by carmenbianca** [comment]
I understand that this needs a code review. Does an analyst also need to verify whether everything still works on the functional side of things?

**Comment by robinkeunen** [comment]
@carmenbianca A code review will be enough for that one. We do not use this ourselves (intended to be used with the connector). @enricostano @danypr92 @cesarlr should take a look though.

**Review by robinkeunen — APPROVED** [review]

**Pull request merged**
