### PR TITLE
[9.0][FIX] easy_my_coop: reorder menu definitions

### PR DESCRIPTION
**Pull request by robinkeunen**
Installing module on an empty database crashes because of the order of import of menus.

I isolated the menus in a separate file and import it at the end.

By the way: cooperative_history_wizard was not loaded, do you know why?

### CODE REVIEW

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
@robinkeunen cooperative history wizard has never been migrated from v7. I don't know if we should keep it or not. For me it could be dropped.

**Comment by houssine78** [comment]
@robinkeunen for me it could be merged.

**Comment by robinkeunen** [comment]
I'd rather have it tested before :-)

**Review by elouan-lb — APPROVED** [review]
Installation from scratch with the fix succeeded, you can merge it !

**Comment by robinkeunen** [comment]
Thanks!

**Comment by vvrossem** [comment]
@robinkeunen could you please remove the branch from gitaggregator conf ? Thanks :)

**Comment by robinkeunen** [comment]
sorry babe

**Comment by robinkeunen** [comment]
done

**Pull request merged**
