### PR TITLE
[12.0] Easy my Coop REST API

### LINKED ISSUE #63: RFC - API Easy My Coop - Investor Wallet Platform
# RFC API Easy My Coop - Investor Wallet Platform

RFC: Request For Comments.

## Context

Coop IT Easy is part of the project _Synergie_ that aims to build a platform for cooperative and citizens. The goal of the platform is  to

- allow citizens to take shares in the participating cooperatives,
- allow cooperatives to manage subscription request from the platform.

The platform code is on GitHub: [investor-wallet-platform](https://github.com/coopiteasy/investor-wallet-platform). It is essentially an extension of Easy My Coop and *depends* on easy my coop.\* 

## Goal

Some cooperatives on the platform already have a tool to manage their subscription. One of these tool is Easy My Coop. The goal of opening an API (on the platform and on Easy My Coop) is 

1. to allow external tool to get subscription requests into their tools
2. Specifically, to allow easy my coop user to manage the subscription from easy my coop and not from the platform.

We're targeting version 12 and up only.

[Easy My Coop documentation](https://docs.google.com/document/d/1sbnoLJOOxBV98x-KTxYqICvZ6gJiLaIncp2riOgfskQ/edit#heading=h.tb6ibqbmam3j)

## Design questions

- Who is pushing / pulling data?
  - I'm leaning towards an API on the platform side
  - EMC will be the source of the actions and maintain mapping between records
  - maybe use https://odoo-connector.com/guides/concepts.html -> mappings
- Odoo [xml-rpc](https://www.odoo.com/documentation/12.0/webservices/odoo.html) or [rest-framework](https://github.com/OCA/rest-framework)?
	- Leaning towards REST
		- Cleaner contracts
		- Easier for non-odoo applications
		- less "out of the box"
		- XXI's century
- On which key are record synchronised?
- swagger and GraphQL?
- Authentification

## Taking a share: flow

The flow to take a share is the following

1. Submitting a subscription request (SR)
2. Validating a SR
	- For a new cooperator
	- For an existing cooperator (capital increase)
3. Record payment
	- creates a share line.

But also, not covered in the first iteration,

- Cancelling a SR
- The cooperator has paid too much or not enough
- Selling back shares
- Subscription register
- Loan management

## Needs - Platform side

Each cooperative only has access to its own data.
Data is transmitted in json format.

1. Get SR list
	- GET 
	- id, name, request date, share, partner, quantity, state
	- filter by date range
	- filter by state (?)
2. Get SR data by id 
	- GET
	- all fields?
3. Validate a request
	- POST
4. Record payment for a capital release
	- POST
	- by id (for request? or invoice? Both?)
	- amount, journal, payment date, memo
	- only full payment for a start?
5. Get cooperator list
	- GET
6. Get cooperator data
	- GET

## Needs - Easy My Coop side

1. Regularly fetch new SR submitted on the platform
2. Fetch new cooperators
2. Post SR validation
3. Post received payment
4. Maintain mapping between records from the platform and Easy My Coop
	- in a table (model, id_iwp, id_emc) + Many2One on records
	- in a field `iwp_key` on the records

For the try: POST a subscription request on EMC

## About Open Sourcing Easy My Coop

EMC was under the AGPL from the start but nothing was made to create a community over the software. 

Developing the API will be the opportunity to

- embark other cooperatives in the adventure (Coopdev, Som Mobilidad, GRAP, ...)
- provide resources necessary for effective contribution (readme, how tos, doc, ...)
- Refactor codebase for maintainability
- Comply with OCA standards.

## Attestation

l’utilisateur de la plateforme doit pouvoir télécharger ses attestations. La question est de savoir si

 1. l’attestation est générée sur la plateforme, téléchargée par l’investisseur,
 2. l’attestation est générée sur l'app de l’entreprise, renvoyée à la plateforme, téléchargée par l’investisseur.

## Additional notes

\* Some parts of easy my coop have been twisted to make synergie possible, fast. We (Robin) are eager to refactor into a cleaner architecture.

### PR DESCRIPTION
**Pull request by robinkeunen**
cf #63 

- [x] Authentification
- [x] Main Bones
- [x] GET subscription request by id
- [x] GET all subscription requests
- [x] GET subscription requests by date range
- [x] POST update on sr status
- [x] GET invoice by id
- [x] POST update invoice status
- [x] POST set invoice as paid
- [x] POST new subcription request

### CODE REVIEW

**Comment by enricostano** [comment]
cc/ @daniquilez

**Comment by enricostano** [comment]
Hi @robinkeunen ! Do you think we could release this module as it is? We would like to start using just `POST new subcription request` endpoint for now. Also if you think that we can help to move this forward please let's talk about it. Thanks!

**Comment by robinkeunen** [comment]
Hi @enricostano ,

I'm scheduled to work on this from the 10th to 14th of August so that should move forward at that time. In the meantime, I think this is functionnal. I'll rebase this on 12.0 and you can start deploying w/ gitaggregator and testing it.

**Comment by enricostano** [comment]
@robinkeunen cool, thanks!

**Comment by danypr92** [comment]
Great job @robinkeunen!! :clap: :clap::clap::clap:

We want to try this module in our staging environments, but we don't use `gitaggregator`.
I publish a `dev` package of this module in PyPI to install it in our staging servers and test it.
You can find the package in https://pypi.org/project/odoo12-addon-easy-my-coop-api/12.0.0.0.1.99.dev13/

Thanks!

**Pull request merged**
