### PR TITLE
12.0 komunigi update translations

### LINKED ISSUE #294: generate all .pot and po (after renaming modules and xml_ids)
there's a good number of translation issues in the document. they can be divided into several categories:

1. expected. the source term was changed/newly introduced/never translated.
2. unexpected. the translation value _differs_ from the translation provided by the module. these need to be either manually fixed or force-updated.
3. differently translated between `fr` and `fr_BE`. Is there a reason these translations are separate?

### PR DESCRIPTION
**Pull request by victor-champonnois**
fix https://github.com/coopiteasy/vertical-cooperative/issues/294

### CODE REVIEW

**Comment by carmenbianca** [comment]
@victor-champonnois  I'm a little bit doubtful that the UPD commits are comprehensive. Did you auto-generate them using the trick from here?

https://github.com/OCA/oca-ci/blob/cffeb8853b2833c5a47da3200b4e3025b47de043/bin/oca_export_and_commit_pot#L15=

**Comment by victor-champonnois** [comment]
@carmenbianca ah no I did not know this trick. I used gettext to make them from the newly exported .po files. I'll check this tool

**Comment by victor-champonnois** [comment]
@carmenbianca actually isn't this trick the one that pushes .pot after the module renaming ? like this one : https://github.com/coopiteasy/vertical-cooperative/commit/acf1ec1a8f82671a596d80cb9bc3e5340f129c7d
If yes, it only changes the module name in the pot file, it doesn't update the translations

**Comment by carmenbianca** [comment]
@victor-champonnois Yes, but it only works on the `12.0` branch, not on `12.0-komunigi`. So there are two options:

1. Change the CI to also generate updated POTs on `12.0-komunigi`. No objections from me, let me know if you'd prefer this and I can make that change easily.
2. Manually generate the POTs using the above script, sometimes.

In both cases I think it'd be a good idea to rebase your work on top of the generated POTs and double-check consistency.

**Comment by victor-champonnois** [comment]
@carmenbianca Sorry I am confused :

> @victor-champonnois Yes, but it only works on the `12.0` branch, not on `12.0-komunigi`. So there are two options:

I don't understand, the commit I mentionned was run by the CI on 12.0-komunigi no, did you change something in the CI since then ?

> In both cases I think it'd be a good idea to rebase your work on top of the generated POTs and double-check consistency.

This branch is on top of 12.0-komunigi, that contains the POT fixing commits, so it's already OK no ?

**Comment by carmenbianca** [comment]
@victor-champonnois Something may have changed since then. But it's also possible that the commits were really done by me pretending to be the CI. In any case, right now, the POTs are not being auto-generated on `12.0-komunigi`. And the POTs that _are_ on `12.0-komunigi` are most likely outdated.

**Comment by victor-champonnois** [comment]
@carmenbianca I ran the script on a blank DB with the modules and the translations installed but it doesn't do anything... I have no error, everything works, but no commits are added... I don't where to go from here.
A way to be sure is to add this CI to 12.0-komunigi, I don't know if it's worth it though, tell me :)

**Comment by carmenbianca** [comment]
@victor-champonnois I ran it. Difference may be that my plain DB had all vertical-cooperative modules installed.

**Comment by victor-champonnois** [comment]
Thanks @carmenbianca !

**Pull request merged**
