### PR TITLE
[12.0][MIG] easy_my_coop_document

### PR DESCRIPTION
**Pull request by elouan-lb**
Straightforward migration. The roadmap indicated to remove dependencies with `easy_my_coop` but I couldn't find any.

### CODE REVIEW

**Comment by houssine78** [comment]
Thanks @elouan-lb 

In fact removing easy_my_coop was meant for the model names and the module name. As it's not close related to easy my coop the aim is to make it a generic module. For me the name should change as well and the module need to move to addons repo.

then maybe we should have a easy_my_coop_document acting as a glue module between easy my coop and the generic module. at least for the menu item.

@robinkeunen @remytms could you give your insights if you have any ;)

**Comment by elouan-lb** [comment]
@houssine78 this is something I could do if needed !

**Comment by houssine78** [comment]
@elouan-lb well, it is something I wouldn't ask if it was for 9.0 but I think that it would be nice and as it's not installed yet in 12 it now or never ;)

**Comment by elouan-lb** [comment]
@houssine78 I moved it and renamed it as `document_hosting` in `addons` repository.

**Review by robinkeunen — APPROVED** [review]

**Review by houssine78 — APPROVED** [review]

**Comment by remytms** [comment]
@elouan-lb As this module do not add items in the `easy_my_coop` menu. You can totally remove it form this repository and move it to `addons`. :)

Thanks for this work. :)

**Review by remytms — CHANGES_REQUESTED** [review]
It seams that this module is now empty. If so, just delete it completely. No need for glue with `emc` if nothing is done for it. For now, no user ask for it.

**Review by remytms — APPROVED** [review]
My bad, I mistaken `easy_my_coop_document_website` for `easy_my_coop_document`.

Thanks for your job. :)

**Comment by houssine78** [comment]
@elouan-lb @remytms where this module is intended to land ? addons or vertical-cooperative ?

**Comment by elouan-lb** [comment]
> @elouan-lb @remytms where this module is intended to land ? addons or vertical-cooperative ?

In `addons`  (https://github.com/coopiteasy/addons/pull/45)

**Comment by houssine78** [comment]
@elouan-lb so this PR cold be closed from my understanding.

**Comment by elouan-lb** [comment]
> @elouan-lb so this PR cold be closed from my understanding.

No, merge is needed to delete easy_my_coop_document from 12.0 repository ! Should I merge it ?

**Comment by houssine78** [comment]
@elouan-lb you're right ! Conflict need to be resolved. I don't know if rebase will do the trick or not. otherwise make a new PR against the latest version of the branch 12.0. see what's essaier for you.

**Comment by elouan-lb** [comment]
> @elouan-lb you're right ! Conflict need to be resolved. I don't know if rebase will do the trick or not. otherwise make a new PR against the latest version of the branch 12.0. see what's essaier for you.

Rebased & merged, thanks !

**Pull request merged**
