### PR TITLE
Implement oca-ci via GitHub Actions

### PR DESCRIPTION
**Pull request by carmenbianca**
Another WIP that tries a different method compared to #182.

### CODE REVIEW

**Comment by carmenbianca** [comment]
Well that took considerably less time than my previous attempt :x

**Comment by carmenbianca** [comment]
The GitHub workflow yaml files are copied almost verbatim from https://github.com/OCA/oca-addons-repo-template/

Forking that repo and using its `copier` mechanism would make life easier.

**Comment by carmenbianca** [comment]
PR is ready; there's a failing test in easy_my_coop that I haven't yet investigated.

**Comment by robinkeunen** [comment]
@carmenbianca merge failing test, it's ok, I'll fix it in Komunigi.

**Comment by carmenbianca** [comment]
@robinkeunen Marked the tests as failing. Will open an issue for the failing tests before merging this.

OK to merge (after squash)?

**Review by robinkeunen — APPROVED** [review]
TIL the "expected failure" decorator 👍 

The failing test is fixed by https://github.com/coopiteasy/vertical-cooperative/pull/202/commits/91025623c5394af025293fb62e6c6b9ece73b4f9

**Pull request merged**
