### PR TITLE
12.0 rename easy my coop be

### LINKED ISSUE #207: Rename `easy_my_coop_be` to `l10n_be_cooperator`
- [x]  Rename `easy_my_coop_be` to `cooperator_be`

Estimated time - 8h

Module contains these functionalities :
- Belgian legal form on partner
- Default values for communications on invoice

### PR DESCRIPTION
**Pull request by victor-champonnois**
[Related issue](https://github.com/coopiteasy/vertical-cooperative/issues/207)

### CODE REVIEW

**Review by robinkeunen — CHANGES_REQUESTED** [review]
Taking a look at these two repositories ([l10n-belgium](https://github.com/OCA/l10n-belgium) and [l10n-france](https://github.com/OCA/l10n-france)), I realise the module should be named `l10n_be_cooperator`. Sorry for the confusion, I renamed other l10n tasks.

**Comment by victor-champonnois** [comment]
- restarted the branch on top of https://github.com/coopiteasy/vertical-cooperative/pull/202
- renamed with l10n_be_cooperator

**Review by carmenbianca — APPROVED** [review]
LGTM

**Review by robinkeunen — APPROVED** [review]

**Review by carmenbianca — CHANGES_REQUESTED** [review]
"name" field in `__manifest__.py` needs to be changed. Check other l10n modules for naming conventions.

**Comment by victor-champonnois** [comment]
@carmenbianca it's fixed, thx :)

**Review by carmenbianca — APPROVED** [review]
approved again ^^ thank you

**Pull request merged**
