### PR TITLE
[12.0] komunigi related refactoring

### PR DESCRIPTION
**Pull request by robinkeunen**
This temporary branch hosts heavy refactoring preliminary to moving modules on the OCA.

### CODE REVIEW

**Comment by robinkeunen** [comment]
Tests from Virginie :

@victor-champonnois 
Tested on https://demain.komunigi.test.coopiteasy.be/
After having added the test ribbon, 
After having set up the right API google recaptcha key on the website administration
After having found the direct link to the form to become cooperator (as there is no direct link on the website menu): https://demain.komunigi.test.coopiteasy.be/become_cooperator
I was able to test the following steps:

- Fill in the form
NOT OK : some texts are in French (Courriel + confirmer l'émail), other still in English. 
Is the PO file alright?

I filled all the fields except the Gender
The Total share is a readonly field and was not updated when I chose 2 shares.

I got a 500: Internal Server Error
When I went back, the Gender field had been set to Masculin without asking me anything.

I stop my test here because even if I fill in everything, I got this 500 internal error.

**Comment by robinkeunen** [comment]
Tests comments from Virginie : 

Tested on https://demain.komunigi.test.coopiteasy.be/
After having added the test ribbon, 
After having set up the right API google recaptcha key on the website administration
After having found the direct link to the form to become cooperator (as there is no direct link on the website menu): https://demain.komunigi.test.coopiteasy.be/become_cooperator
I was able to test the following steps:

- Fill in the form
NOT OK : some texts are in French (Courriel + confirmer l'émail), other still in English. 
Is the PO file alright?

I filled all the fields except the Gender
The Total share is a readonly field and was not updated when I chose 2 shares.

I got a 500: Internal Server Error
When I went back, the Gender field had been set to Masculin without asking me anything.

I stop my test here because even if I fill in everything, I got this 500 internal error.

**Comment by victor-champonnois** [comment]
> Tests from Virginie :
> 
> @victor-champonnois Tested on https://demain.komunigi.test.coopiteasy.be/ After having added the test ribbon, After having set up the right API google recaptcha key on the website administration After having found the direct link to the form to become cooperator (as there is no direct link on the website menu): https://demain.komunigi.test.coopiteasy.be/become_cooperator I was able to test the following steps:
> 
>     * Fill in the form
>       NOT OK : some texts are in French (Courriel + confirmer l'émail), other still in English.
>       Is the PO file alright?
Fixed by syncing the fr translation and by [this PR](https://github.com/coopiteasy/vertical-cooperative/pull/249) : 
> 
> 
> I filled all the fields except the Gender The Total share is a readonly field and was not updated when I chose 2 shares.

Le champs total share se met à jour maintenant, je ne sais pas à quoi l'erreur que tu soulève était dû..

> 
> I got a 500: Internal Server Error When I went back, the Gender field had been set to Masculin without asking me anything.

Yes there is indeed an error, if the field gender is left blank, it is interpreted as "male". So going back to the form display the value "male". This is fixed in https://github.com/coopiteasy/vertical-cooperative/pull/250. Note : with this fixed the gender field cannot be left empty. 
The fix is not deployed in komunigi for now

> 
> I stop my test here because even if I fill in everything, I got this 500 internal error.

Fixed, I no longer get 500 error when sending the form.

**Comment by victor-champonnois** [comment]
@cathLemb @vdewulf @polchampion 
All the bugs are fixed and deployed at https://lenid.komunigi.test.coopiteasy.be/ (not on the other DBs) ! Ready to continue testing
Note : I updated the translation

**Comment by robinkeunen** [comment]
@vdewulf @polchampion @cathLemb Les derniers développements sont déployés ici : 

https://blank.komunigi.test.coopiteasy.be/web/database/selector
https://brasseriedurenard.komunigi.test.coopiteasy.be/web/database/selector
https://demain.komunigi.test.coopiteasy.be/web/database/selector
https://lenid.komunigi.test.coopiteasy.be/web/database/selector
https://oufticoop.komunigi.test.coopiteasy.be/web/database/selector
https://synergie.komunigi.test.coopiteasy.be/web/database/selector

Il faut toujours tester sur les bases de données qui se terminent par `renamedep`.

Il ne restera alors plus que la tache https://github.com/coopiteasy/vertical-cooperative/pull/257 dans l'étape de renommage (les `loan` sont laissés de coté pour le moment et on attend financité pour le module `easy_my_coop_connector`)

**Comment by victor-champonnois** [comment]
PR to merge in other repos when merging this one:
- Obeesdoo -> 12.0-komunigi
- investor-wallet-platform -> 12.0-rename-easy_my_coop

**Pull request merged**
