### PR TITLE
[FIX] partner_vals was replaced by call to function.

### PR DESCRIPTION
**Pull request by houssine78**

### CODE REVIEW

**Review by mclaeysb — CHANGES_REQUESTED** [review]
Cool que tu aies trouver. Malheureusement, le diff est le fichier total > c'est pas propre dans git et je ne sais pas inspecter tes changements!

**Comment by mclaeysb** [comment]
For your information: the infra CI gave a merge error wrt this branch - probably due to the complete diff mentionned above.

**Comment by houssine78** [comment]
@mclaeysb I fixed my editor problem and I made this PR came back from the deads !

**Review by mclaeysb — COMMENTED** [review]
Awesome resurrection!
I understand. One question though.

**Comment by mclaeysb** [comment]
I see my question was not saved. Here it is: I know the `update()` function for a dictionnary in python, but not the `replace()` function. Shouldn't the `replace()` also be `update()`?

**Comment by houssine78** [comment]
@mclaeysb you're right it should be update not replace.

**Comment by houssine78** [comment]
@mclaeysb I've fixed the wrong function call.

**Comment by mclaeysb** [comment]
I approve! Let's merge this!

**Pull request merged**
