### PR TITLE
[14.0][MIG] cooperator_website_recaptcha

### PR DESCRIPTION
**Pull request by carmenbianca**
## Description

Depends on #338

## Odoo task (if applicable)

https://gestion.coopiteasy.be/web#id=8914&action=475&active_id=260&model=project.task&view_type=form&menu_id=

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

### CODE REVIEW

**Comment by victor-champonnois** [comment]
~~@carmenbianca oups, there was a misunderstanding here, this module is deprecated, it is replaced by portal_recaptcha...~~

**Comment by victor-champonnois** [comment]
@carmenbianca nevermind I got confused

**Review by huguesdk — APPROVED** [review]

**Review by carmenbianca — COMMENTED** [review]
LGTM

**Pull request merged**
