### PR TITLE
[REM] cooperator: Unique bank constraint on partner

### LINKED ISSUE #241: Remove disabled constraint unique_number on res.partner.bank
OCA won't accept this disabled constraint. We should move it to a custom module or sanitise our clients' databases.

https://gestion.coopiteasy.be/web#id=9262&action=475&active_id=221&model=project.task&view_type=form&menu_id=536

Fixed by https://github.com/coopiteasy/vertical-cooperative/pull/310

Replaced by https://github.com/coopiteasy/addons/pull/226

- [x] deploy in test
- [x] notify Pol
- [ ] merge 
- [ ] and port to 14.0

### PR DESCRIPTION
**Pull request by carmenbianca**
## Description

Fixes #241, related to https://github.com/coopiteasy/addons/pull/226

Merging this implies that `partner_no_unique_bank` effectively _must_ be installed on all databases that use EMC/cooperator unless we sanitise them.

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] (If a new module) Moving this to OCA has been considered.

### CODE REVIEW

**Comment by robinkeunen** [comment]
@carmenbianca please notify the analysts of this _functional change_ :-)

**Review by robinkeunen — APPROVED** [review]

**Comment by polchampion** [comment]
@carmenbianca Sucessfully installed `partner_no_unique_bank`. Note that `cooperator` migration in test did not lead to critical issues. As migration was done already, we can't test what its effect is when `partner_no_unique_bank` is already installed alongside `easy_my_coop`. I don't believe it should be specifically tested though.

Can you ping me when `partner_no_unique_bank` is pushed to 12P ?

**Review by robinkeunen — APPROVED** [review]
Ok but needs a rebase

**Comment by polchampion** [comment]
@carmenbianca @robinkeunen If you need me to install `partner_no_unique_bank` on the following db, please ping me when it is in prod.

bcl
bloum
brasseriedelorne
brasseriedurenard
coopeco
coopeco-formation
coopeos
coopiteasy
demo-oufticoop
lafinca
lenid
lepedalo
lesptitspots
mazette
oufticoop
vervicoop
bees
lafeve
chaf

**Comment by carmenbianca** [comment]
@huguesdk This will need to be forward-ported to 14.0 at some point.

**Comment by huguesdk** [comment]
@carmenbianca would you please check why the tests on merge fail and fix the problem?

**Comment by carmenbianca** [comment]
@huguesdk will do. I'll take charge on this collection of issues. They're not meant to be merged yet; functional review was never done.

**Review by robinkeunen — CHANGES_REQUESTED** [review]
needs to be moved to oca/cooperative. removing it from gitaggregator.

**Comment by huguesdk** [comment]
@carmenbianca would you please create pull requests for 12.0 and 14.0 in [OCA/cooperative](https://github.com/OCA/cooperative) with the same changes? removing the unique constraint on bank accounts makes the tests for OCA/l10n-belgium#150 fail.

**Comment by huguesdk** [comment]
please note that this change will need a migration script to re-add the sql constraint.

**Comment by robinkeunen** [comment]
done here https://github.com/OCA/cooperative/pull/32

**Pull request closed without merging**
